apiVersion: v1
kind: Pod
metadata:
  name: readiness
  labels:
    app: readiness
spec:
  containers:
  - name: readiness
    image: aj5002/tasksapp-python:1.0
    ports:
    - containerPort: 5000
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10